authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
  path('login/', authapp.login, name='login'),
  path('logout/', authapp.logout, name='logout'),
  path('register/', authapp.register, name='register'),
  path('edit/', authapp.edit, name='edit'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.index, name="main"),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', admin.site.urls),
] 

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class ShopUser(AbstractUser):
  avatar = models.ImageField(upload_to="users_avatars", blank=True)
  age = models.PositiveIntegerField(verbose_name="age", null=True, blank=True)
  

mainapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Product(models.Model):
  name = models.CharField(max_length=150, verbose_name="Name")
  image = models.ImageField(blank=True, upload_to='products')
  short_name = models.CharField(max_length=150, verbose_name="Short_name", default="")
  short_desc = models.CharField(max_length=250, blank=True)
  description = models.TextField(verbose_name="description")
  price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="price", default=0)
  quantity = models.PositiveIntegerField(default=0, verbose_name="quantity")
  def __str__(self):
    return self.name
  

authapp/forms.py
from typing import Any
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import ShopUser

class ShopUserLoginForm(AuthenticationForm):
  class Meta:
    model = ShopUser
    fields = ('username', 'password')

  def __init__(self, *args, **kwargs):
    super(ShopUserLoginForm, self).__init__(*args, **kwargs)
    self.fields["username"].widget.attrs["placeholder"] = "login"
    self.fields["password"].widget.attrs["placeholder"] = "password"
    for field_name, field in self.fields.items():
        field.widget.attrs['class'] = 'input_admin_login'

class ShopUserRegistrForm(UserCreationForm):
  class Meta:
    model = ShopUser
    fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')
  
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    placeholder_list = {'username':'username', 'first_name':'first_name', 'password1':'password', 'password2':'password again', 'email':'email', 'age':'age', 'avatar':'avatar'}
    for name, placeholder in placeholder_list.items():
      self.fields[name].widget.attrs["placeholder"] = placeholder
    for fieald_name, field in self.fields.items():
      field.widget.attrs['class'] = 'menu_item_element'
      field.help_text = ''
  
  # def clean_age(self):
  #   data = self.cleaned_data['age']
  #   if data < 18:
  #     raise forms.ValidationError("Вы слишком молоды!")
  #   return data

    

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import ShopUserLoginForm, ShopUserRegistrForm
from django.contrib import auth
from django.urls import reverse


def login(request):
  title = "login"

  login_form = ShopUserLoginForm(data=request.POST)
  if request.method == 'POST' and login_form.is_valid():
    username = request.POST['username']
    password = request.POST['password']

    user = auth.authenticate(username=username, password=password)
    if user and user.is_active:
      auth.login(request, user)
      return HttpResponseRedirect(reverse('main'))
    
  content = {'title': title, 'login_form':login_form}
  return render(request, 'authapp/login.html', content)

def logout(request):
  auth.logout(request)
  return HttpResponseRedirect(reverse('main'))

def register(request):
  title = 'Регистрация'

  if request.method == "POST":
    register_form = ShopUserRegistrForm(request.POST, request.FILES)

    if register_form.is_valid():
      register_form.save()
      return HttpResponseRedirect(reverse('authapp:login'))
  else:
    register_form = ShopUserRegistrForm()
  context = {
    'title':title,
    'register_form': register_form
  }

  return render(request, 'authapp/register.html', context)

def edit(request):
  return HttpResponseRedirect(reverse('main'))

mainapp/views.py
from django.shortcuts import render
from mainapp.models import Product

def index(request):
  product_list = Product.objects.all()
  
  context = {
    'products': product_list
  }

  return render(request, 'mainapp/index.html', context)

authapp/templates/authapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Playfair+Display:ital@0;1&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %} ">
  {% block extra_style %}
  {% endblock %}
</head>
<body>
{% block content%}
{% endblock %}
</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block extra_style %}
  <link rel="stylesheet" href="{% static 'css/style_login.css' %}">
{% endblock %}
{% block content %}
  <div class="authorization">
    <div class="container">
      <div class="auth_inner">
        <div class="login">
          <h2 class="h2 text-center head">
          Вход в систему
          </h2>
        </div>
        {% csrf_token %}
        <form  method="POST" class="adminlogin">
          {% csrf_token %}
          <div class="login">
            {{ login_form.username }}
          </div>
          <div class="password">
            {{ login_form.password }}
          </div>
          <div class="login__button">
            <button class="button__item">
              <a href="{% url 'auth:login' %}" class="button_item_link">Sign in</a> 
            </button>
            <button class="button__item" >
              <a href="{% url 'auth:register' %}" class="button_item_link">Sign up</a> 
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block extra_style %}
  <link rel="stylesheet" href="{% static 'css/style_login.css' %}">
{% endblock %}
{% block content %}
  <div class="authorization">
    <div class="container">
      <div class="auth_inner">
        <div class="login">
          <h2 class="h2 text-center head">
          Регистрация
          </h2>
        </div>
        {% csrf_token %}
        <form  method="POST" class="adminlogin"  enctype="multipart/form-data">
          
          <ul class="registr_menu">
            {% csrf_token %}
            <li class="menu_item">
              {{ register_form.username }}
            </li>
            <li class="menu_item">
              {{ register_form.first_name }}
            </li>
            <li class="menu_item">
              {{ register_form.password1 }}
            </li>
            <li class="menu_item">
              {{ register_form.password2 }}
            </li>
            <li class="menu_item">
              {{ register_form.email }}
            </li>
            <li class="menu_item">
              {{ register_form.age }}
            </li>
            <li class="menu_item">
              <div class="avavtar">
                {{ register_form.avatar }}
              </div>
              
            </li>
          
          </ul>
          <div class="login__button">
            <input class="button__item" type="submit" value="Sign up">
            <button class="button__item" >
              <a href="{% url 'auth:login' %}" class="button_item_link">Back</a> 
            </button>
          </div>
          
        </form>
        
       
      </div>
    </div>
  </div>
{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block css %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Playfair+Display:ital@0;1&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}

 
    <title>Document</title>
</head>
<body>
<header class="header">
    <div class="container">
        <div class="header_inner">
            <a href="#" class="logo">
                <img src="{% static 'images/logo.svg' %}" alt="">
            </a>
            <h3 class="header_title">LA COLLECTION PRIVÉE CHRISTIAN DIOR</h3>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}" class="User">logout</a>
            {% else %}
                <a href="{% url 'auth:login' %}" class="User">login</a>
            {% endif %}
            {{user}}

            <!-- <nav class="menu">
                <ul class="menu_list">
                    <li class="menu_item">
                        <a href="#" class="menu_link">WOMEN'S FRAGRANCE</a>
                    </li>
                    <li class="menu_item">
                        <a href="#" class="menu_link">MEN'S FRAGRANCE</a>
                    </li>
                    <li class="menu_item">
                        <a href="#" class="menu_link">MAKEUP</a>
                    </li>
                    <li class="menu_item">
                        <a href="#" class="menu_link">SKINCARE</a>
                    </li>
                    <li class="menu_item">
                        <a href="#" class="menu_link">DIOR SPA</a>
                    </li>
                </ul>
            </nav> -->
            <ul class="user_nav">
                <li class="user_nav_item">
                    <a href="" class="user_nav_link">
                        <img src="{% static 'images/favorites.svg' %}" alt="like">
                    </a>
                </li>
                <li class="user_nav_item">
                    <a href="" class="user_nav_link">
                        <img src="{% static 'images/cart.svg' %}" alt="basket">
                    </a>
                </li>
            </ul>
        </div>
    </div>
</header>
{% block content %}

{% endblock %}
<div class="footer">
    <div class="container">
        <div class="footer_inner">
            <div class="footer_top">
                <a href="#" class="footer_logo">
                    <img src="{% static 'images/logo.svg' %}" alt="">
                </a>
                <img src="{% static 'images/footer-decor.jpg' %}" alt="" class="footer_img">
                <div class="footer_items">
                    <div class="footer_item">
                        <h5 class="footer_item_title">
                            SIGN UP FOR EXCLUSIVITY 
                        </h5>
                        <form action="#" class="footer_item_form">
                            <input class="footer_item_input" type="email" placeholder="E-mail">
                            <button class="footer_item_btn" type="submit">
                                <img src="{% static 'images/arrow-right.svg' %}" alt="">
                            </button>
                        </form>
                    </div>
                     <div class="footer_item">
                        <h5 class="footer_item_title">
                            FIND A BOUTIQUE
                        </h5>
                        <ul class="footer_item_list">
                            <li>
                                <a href="#" class="footer_item_link">
                                    Parfums Christian Dior Boutiques
                                </a>
                            </li>
                            <li>
                                <a href="#" class="footer_item_link">
                                    Christian Dior Couture Boutiques
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer_item">
                        <h5 class="footer_item_title">
                            CLIENT SERVICES
                        </h5>
                        <ul class="footer_item_list">
                            <li>
                                <a href="#" class="footer_item_link">
                                    Contact Parfums Christian Dior
                                </a>
                            </li>
                            <li>
                                <a href="#" class="footer_item_link">
                                    Delivery & Returns
                                </a>
                            </li>
                            <li>
                                <a href="#" class="footer_item_link">
                                    FAQ
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <ul class="footer_social_list">
                    <li class="footer_social_item">
                        <a href="#" class="footer_social_link">
                            <img src="static/images/social/youtube.svg" alt="">
                        </a>
                    </li>
                    <li class="footer_social_item">
                        <a href="#" class="footer_social_link">
                            <img src="static/images/social/twiter.svg" alt="">
                        </a>
                    </li>
                    <li class="footer_social_item">
                        <a href="#" class="footer_social_link">
                            <img src="static/images/social/facebook.svg" alt="">
                        </a>
                    </li>
                    <li class="footer_social_item">
                        <a href="#" class="footer_social_link">
                            <img src="static/images/social/instagram.svg" alt="">
                        </a>
                    </li>
                </ul>
            </div>
            <div class="footer_nav">
                <ul class="footer_nav_list">
                    <li class="footer_nav_item">
                        <a href="#" class="footer_nav_link">
                            Legal Terms and Conditions
                        </a>
                    </li>
                    <li class="footer_nav_item">
                        <a href="#" class="footer_nav_link">
                            Data Protection
                        </a>
                    </li>
                    <li class="footer_nav_item">
                        <a href="#" class="footer_nav_link">
                            Personalize my choices
                        </a>
                    </li>
                    <li class="footer_nav_item">
                        <a href="#" class="footer_nav_link">
                            General Sales Conditions
                        </a>
                    </li>
                    <li class="footer_nav_item">
                        <a href="#" class="footer_nav_link">
                            Ethics & compliance
                        </a>
                    </li>
                    <li class="footer_nav_item">
                        <a href="#" class="footer_nav_link">
                            Careers
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

</body>
<script src="{% static 'js/swiper-bundle.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<section class="top">
    <div class="top_swiper swiper">
      <div class="swiper-wrapper">
        <div class="swiper-slide">
            <div class="top_slide">
                <div class="container">
                    <div class="top_slide_inner">
                        <img src="{% static 'images/slider-top/slider-1.jpg' %}" alt="">
                        <div class="top_slide_content">
                            <h1 class="top_slide_title">
                                GRIS DIOR
                            </h1>
                            <p class="top_slide_subtitle">
                                Fragrance
                            </p>
                            <p class="top_slide_text">
                                With Gris Dior you dare to reveal your most surprising, mysterious and unexpected facets.
                            </p>
                            <a href="#" class="top_slide_btn button">
                                DISCOVER
                            </a>
                        </div>
                        <img src="{% static 'images/slider-top/slider-2.jpg' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
        <div class="swiper-slide">
            <div class="top_slide" style="background-image: url(/static/images/slider-top/slide-bg-1.jpg);">
                <div class="container">
                    <div class="top_slide_inner">
                        <a href="#" class="top_slide_btn button">
                            YOUR NEW EXPERIENCE 
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="swiper-slide">
            <div class="top_slide" style="background-image: url(/static/images/slider-top/slide-bg-2.jpg);">
                <div class="container">
                    <div class="top_slide_inner">
                        <a href="#" class="top_slide_btn button">
                            YOUR NEW EXPERIENCE
                        </a>
                    </div>
                </div>
            </div>
        </div>
        ...
      </div>
      
      <div class="container container-arrow">
        <div class="swiper-button-prev">
            <img src="{% static 'images/arrow-left.svg' %}" alt="">
          </div>
          <div class="swiper-button-next">
            <img src="{% static 'images/arrow-right.svg' %}" alt="">
          </div>
      </div>

    </div>
</section>
<section class="about">
    <div class="container">
        <div class="about_inner">
                <div class="about_title">
                    DARE IN 
                    GRIS DIOR
                </div>
                <div class="about_textbox">
                    <div class="about_text">
                        <p>
                            Gris Dior is the olfactory expression of gray, the iconic color of the House of Dior that embodies the bold spirit of Christian Dior.
                        </p>
                        <p>
                            A unisex eau de parfum that defies gender, Gris Dior is an intense chypre fragrance that makes a strong, recognizable statement, a fragrance you adopt and interpret to suit your own rules.
                        </p>
                        <p>
                            Gris Dior uninhibitedly combines heritage with a modern twist and plays the unisex card with confidence. It is multifaceted and not as obvious as it seems, like the color gray, richly nuanced with its subtleties, anything but a simple mix of black and white.
                        </p>
                    </div>
                    <div class="about_text about_text--bold">
                        <p>
                            A backdrop for all desires, revealing all shades: dare to go gray with Gris Dior. 
                        </p>
                        <p>
                            A bold embodiment of this elusive color, Gris Dior is a light chypre fragrance that has become an icon, an unexpected master of the game. Both a fragrance for women and a fragrance for men, its unisex trail invites uninhibited expression today.
                        </p>
                    </div>
                </div>

                <div class="about_slider swiper">
                    <div class="swiper-wrapper">
                    <div class="swiper-slide">
                    <div class="about_item">
                        <h4 class="about_item_title">
                            DISCOVER GRIS DIOR
                        </h4>
                        <img src="{% static 'images/about-slider/1.jpg' %}" alt="">
                    </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="about_item">
                            <h4 class="about_item_title">
                                DARE TO RISK IT
                            </h4>
                            <img src="{% static 'images/about-slider/2.jpg' %}" alt="">
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="about_item">
                            <h4 class="about_item_title">
                                FEEL THE FLAVOUR
                            </h4>
                            <img src="{% static 'images/about-slider/3.jpg' %}" alt="">
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="about_item">
                        <h4 class="about_item_title">
                            DISCOVER GRIS DIOR
                        </h4>
                        <img src="{% static 'images/about-slider/4.jpg' %}" alt="">
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="about_item">
                            <h4 class="about_item_title">
                                DARE TO RISK IT
                            </h4>
                            <img src="{% static 'images/about-slider/1.jpg' %}" alt="">
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="about_item">
                            <h4 class="about_item_title">
                                FEEL THE FLAVOUR
                            </h4>
                            <img src="{% static 'images/about-slider/2.jpg' %}" alt="">
                        </div>
                    </div>
                    </div>
                    <div class="container-arrow about_arrow">
                        <div class="swiper-button-prev">
                            <img src="{% static 'images/arrow-left.svg' %}" alt="">
                        </div>
                        <div class="swiper-button-next">
                            <img src="{% static 'images/arrow-right.svg' %}" alt="">
                        </div>
                    </div>
                </div>
                <a href="#" class="about_btn button">
                    SHOW ME MORE
                </a>
        </div>
    </div>
</section>
<div class="accordion">
    <div class="container">
        <div class="accordion_inner">
            <div class="accordion_item">
                <div class="accordion_triger">
                    <p class="accordion_triger_title">
                        DESCRIPTION
                    </p>
                    <p class="accordion_triger_text">
                        Gris Dior is the olfactory expression of gray, the iconic color of the House of Dior that embodies the bold spirit of Christian Dior.
                    </p>
                </div>
                <div class="accordion_content">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum, accusamus vitae.
                         Dignissimos ullam sed, adipisci consequatur minima veritatis odio tempora odit nobis, fuga cum aut commodi quidem aliquam perspiciatis quaerat.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum, accusamus vitae.
                         Dignissimos ullam sed, adipisci consequatur minima veritatis odio tempora odit nobis, fuga cum aut commodi quidem aliquam perspiciatis quaerat.
                    </p>
                </div>
              
            </div>
            <div class="accordion_item">
                <div class="accordion_triger">
                    <p class="accordion_triger_title">
                        PERFUMER'S WORD
                    </p>
                    <p class="accordion_triger_text">
                        "What if the Dior gray were a fragrance? This emphatic gray is not merely a mix of black and white, but the result of a chromatic blend.”
                    </p>
                </div>
                <div class="accordion_content">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum, accusamus vitae.
                         Dignissimos ullam sed, adipisci consequatur minima veritatis odio tempora odit nobis, fuga cum aut commodi quidem aliquam perspiciatis quaerat.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum, accusamus vitae.
                         Dignissimos ullam sed, adipisci consequatur minima veritatis odio tempora odit nobis, fuga cum aut commodi quidem aliquam perspiciatis quaerat.
                    </p>
                </div>
               
            </div>
            <div class="accordion_item">
                <div class="accordion_triger">
                    <p class="accordion_triger_title">
                        APPLICATION TIPS
                    </p>
                    <p class="accordion_triger_text">
                        Spray Gris Dior on pulse points: neck and wrists.
                    </p>
                </div>
                <div class="accordion_content">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum, accusamus vitae.
                         Dignissimos ullam sed, adipisci consequatur minima veritatis odio tempora odit nobis, fuga cum aut commodi quidem aliquam perspiciatis quaerat.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum, accusamus vitae.
                         Dignissimos ullam sed, adipisci consequatur minima veritatis odio tempora odit nobis, fuga cum aut commodi quidem aliquam perspiciatis quaerat.
                    </p>
                </div>
               
            </div>
            <div class="accordion_item">
                <div class="accordion_triger">
                    <p class="accordion_triger_title">
                        INGREDIENTS
                    </p>
                   
                </div>
                <div class="accordion_content">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum, accusamus vitae.
                         Dignissimos ullam sed, adipisci consequatur minima veritatis odio tempora odit nobis, fuga cum aut commodi quidem aliquam perspiciatis quaerat.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum, accusamus vitae.
                         Dignissimos ullam sed, adipisci consequatur minima veritatis odio tempora odit nobis, fuga cum aut commodi quidem aliquam perspiciatis quaerat.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="products">
    <div class="container">
        <div class="products_inner">
            <p class="products_title">WHAT ELSE?</p>
            <div class="products_items">
                {% for product in products %}
                <div class="products_item">
                    <p class="product_item_step">{{ product.short_name }}</p>
                    <img class="products_item_img" src="{{ product.image.url }}" alt="">
                    <p class="product_item_name">
                        <span>{{ product.name }}</span>
                        {{ product.short_desc }}
                    </p>
                    <p class="product_item_price">
                        {{ product.price }}€
                    </p>
                </div>
                {% endfor %}
                <!-- <div class="products_item">
                    <p class="product_item_step">02 CONTINUE THE RITUAL</p>
                    <img class="products_item_img" src="{% static 'images/products/2.jpg' %}" alt="">
                    <p class="product_item_name">
                        <span>GRIS DIOR</span>
                        Unisex Eau de Parfum 
                    </p>
                    <p class="product_item_price">
                        265€
                    </p>
                </div>
                <div class="products_item">
                    <p class="product_item_step">03 ADD THE FINISHING TOUCH</p>
                    <img class="products_item_img" src="{% static 'images/products/3.jpg' %}" alt="">
                    <p class="product_item_name">
                        <span>GRIS DIOR</span>
                        Hair Perfume
                    </p>
                    <p class="product_item_price">
                        102€
                    </p>
                </div> -->
            </div>
        </div>
    </div>
</div>
{% endblock %}